[package]
name = "erigon-db"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7"
arrayref = "0.3"
bytes = "1"
derive_more = "0.99"
eyre = "0.6.5"
ethers = { git = "https://github.com/gakonst/ethers-rs" }
mdbx = { package = "libmdbx", version = "0.1" }

[patch.crates-io]
libmdbx = { path = "../ext/libmdbx-rs" }
